name: HotkeyManager
main: com.gmail.bobason01.HotkeyManager
description: Custom Hotkey Manager
author: crston
version: 2.0
api-version: 1.16
depend: [ProtocolLib]
commands:
  hotkeyreload:
    description: Reloads the hotkey configuration.
    usage: /hotkeyreload
    permission: hotkeymanager.reload