name: HotkeyManager
main: com.gmail.bobason01.HotkeyManager
description: Custom Hotkey Manager
author: crston
version: 1.1
api-version: 1.16
depend: [ProtocolLib]
commands:
  hotkeyreload:
    description: Reload HotkeyManager config
    permission: hotkeymanager.reload
    usage: /hotkeyreload
